apiVersion: v1
kind: Namespace
metadata:
  name: rollout-numalogic-demo
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: numalogic-rollout-demo
  labels:
    app: numalogic-rollout-demo
spec:
  replicas: 6
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: numalogic-rollout-demo
  strategy:
    canary:
      analysis:
        args:
          - name: ingress
            value: canary-demo
          # pod template hash from the latest ReplicaSet
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
        # Template options: error-rate-anomaly, latency-anomaly, unified-anomaly
        templates:
          - templateName: unified-anomaly
        startingStep: 1 
      canaryService: rollout-demo-app-canary-service
      stableService: rollout-demo-app-stable-service
      steps:
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: numalogic-rollout-demo
    spec:
      volumes:
        - name: log-config-volume
          configMap:
            name: demo-log-config
      containers:
        - name: app
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VERSION
              value: "octo"
          image: quay.io/numaio/numalogic-demo:puffy-1
          args:
            - --logconfig
            - /etc/config/config.yaml
            - --logenable
            - "true"
          imagePullPolicy: Always
          volumeMounts:
            - name: log-config-volume
              mountPath: /etc/config
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
            - containerPort: 8490
              name: metric
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              scheme: HTTPS
#              port: 8080
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              scheme: HTTPS
#              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 5Mi
            limits:
              cpu: 200m
              memory: 25Mi
---
apiVersion: v1
kind: Service
metadata:
  name: numalogic-demo-service
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    iks-metric: http-metrics
  name: numalogic-demo-service-metrics
spec:
  ports:
    - name: iks-metric
      port: 8490
      protocol: TCP
      targetPort: 8490
  selector:
    app: numalogic-rollout-demo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-stable-service
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-canary-service
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
