apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-rollout-numalogic-demo
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: numalogic-rollout-demo
  namespace: sandbox-rollout-numalogic-demo
  labels:
    app: numalogic-rollout-demo
    app.kubernetes.io/instance: numalogic-rollout-demo
    applications.argoproj.io/app-name: numalogic-demo
    assetAlias: Intuit.sandbox.sandbox.numalogicdemo
    assetId: '4975369280839883999'
    buildType: maven
    env: demo-usw2-eks
    l1: sandbox
    l2: sandbox
spec:
  replicas: 6
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: numalogic-rollout-demo
  strategy:
    canary:
      analysis:
        args:
          - name: ingress
            value: canary-demo
          # pod template hash from the latest ReplicaSet
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
        # Template options: error-rate-anomaly, latency-anomaly, unified-anomaly
        templates:
          - templateName: unified-anomaly
        startingStep: 1 
      canaryService: rollout-demo-app-canary-service
      stableService: rollout-demo-app-stable-service
      steps:
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: numalogic-rollout-demo
        applications.argoproj.io/app-name: numalogic-rollout-demo
        asset: Intuit.sandbox.sandbox.demorestapp
        assetAlias: Intuit.sandbox.sandbox.demorestapp
        assetId: '4975369280839883999'
        env: qal
        istio-injected: 'true'
        l1: sandbox
        l2: sandbox
    spec:
      containers:
        - name: app
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VERSION
              value: "octoerrrrorrrrr"
          image: quay.io/numaio/numalogic-demo:octoerror
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
            - containerPort: 8490
              name: metric
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: numalogic-demo-service
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    iks-metric: actuator-prometheus
  name: numalogic-demo-service-metrics
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: iks-metric
      port: 8490
      protocol: TCP
      targetPort: 8490
  selector:
    app: numalogic-rollout-demo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-stable-service
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-canary-service
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
