apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-numalogic-techcon-demo
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numalogic-demo-deployment
  namespace: sandbox-numalogic-techcon-demo
  labels:
    app: numalogic-techcon-demo
    app.kubernetes.io/instance: numalogic-techcon-demo
    applications.argoproj.io/app-name: numalogic-demo
    assetAlias: Intuit.sandbox.sandbox.numalogicdemo
    assetId: '4975369280839883999'
    buildType: maven
    env: demo-usw2-eks
    l1: sandbox
    l2: sandbox
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: numalogic-techcon-demo
  template:
    metadata:
      labels:
        app: numalogic-techcon-demo
        applications.argoproj.io/app-name: numalogic-techcon-demo
        asset: Intuit.sandbox.sandbox.demorestapp
        assetAlias: Intuit.sandbox.sandbox.demorestapp
        assetId: '4975369280839883999'
        env: qal
        istio-injected: 'true'
        l1: sandbox
        l2: sandbox
    spec:
      containers:
        - name: app
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/sarabala1979/numalogic-demo:purple-error
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
            - containerPort: 8490
              name: metric
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
  minReadySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: numalogic-demo-service
  namespace: sandbox-numalogic-techcon-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-techcon-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    iks-metric: actuator-prometheus
  name: numalogic-demo-service-metrics
  namespace: sandbox-numalogic-techcon-demo
spec:
  clusterIP: 172.20.63.130
  clusterIPs:
    - 172.20.63.130
  ports:
    - name: iks-metric
      port: 8490
      protocol: TCP
      targetPort: 8490
  selector:
    app: numalogic-techcon-demo
  type: ClusterIP
