apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-anomaly
  namespace: sandbox-rollout-numalogic-demo
spec:
  args:
    - name: stable-hash
    - name: canary-hash
    - name: initial-delay
      value: 120s
    - name: count
      value: '20'
    - name: interval
      value: 5s
    - name: failure-limit
      value: '3'
    - name: inconclusive-limit
      value: '3'
  metrics:
    - name: latency-anomaly
      count: '{{args.count}}'
      failureLimit: '{{args.failure-limit}}'
      inconclusiveLimit: '{{args.inconclusive-limit}}'
      initialDelay: '{{args.initial-delay}}'
      interval: '{{args.interval}}'
      successCondition: result[0] < 3
      provider:
        prometheus:
          address: 'http://prometheus-service.monitoring.svc.cluster.local:8080'
          query: >+
            namespace_rollout_hash_latency_anomaly{namespace="sandbox-numalogic-techcon-demo", hash_id="{{args.canary-hash}}"}
